### ISSUE TITLE
Url estranha quando erro na pesquisa

### ISSUE THREAD

**Issue by diksown** [Projeto-USPY/uspy-contributions#12]
Primeiramente, obrigado pelo projeto! Os desenvolvedores estão de parabéns. A interface gráfica é muito bonita e fluida, a ideia é genial e acredito que será muito útil para a comunidade. 

**Problema:**
Quando eu tentei colocar uma matéria não existente na barra de pesquisa e cliquei em enter, o site me levou pra uma url estranha (uspy.me/Disciplinas/undefined/undefined/undefined). O erro também acontece se eu digitar o nome de uma matéria que existe, mas não selecionar uma opção com as teclas (↑↓)
![2021-03-31_13-10](https://user-images.githubusercontent.com/49994083/113176885-55725900-9223-11eb-9b33-ed8942da3875.png)
![2021-03-31_13-11](https://user-images.githubusercontent.com/49994083/113176899-5905e000-9223-11eb-8e51-90355febebfa.png)

**Solução**
Acredito que seria mais interessante checar que a disciplina não existe, na mesma página, pra os "undefined" não assustarem. Segue abaixo um exemplo de como ficaria na interface gráfica. E no caso de existir alguma matéria com esse nome, fazer com que eu entre na página dessa matéria quando eu apertar enter.
![erro](https://user-images.githubusercontent.com/49994083/113177714-332d0b00-9224-11eb-8859-fede6cb7e0bc.png)

**Comment by lucasturci** [comment]
Valeu @diksown !
